// Generated by CoffeeScript 1.7.1
(function() {
  var TimedCreative;

  TimedCreative = (function() {
    function TimedCreative(startDate, endDate, callback) {
      var day, month, now, theDate, year;
      this.startDate = startDate;
      this.endDate = endDate;
      this.callback = callback;
      now = new Date();
      year = now.getFullYear();
      month = now.getMonth() + 1;
      day = now.getDate();
      if (month < 10) {
        month = "0" + month;
      }
      if (day < 10) {
        day = "0" + day;
      }
      theDate = parseInt(year + month + day);
      if (!(this.startDate === 0 && this.endDate === 0) && (this.callback != null)) {
        if (this.startDate === 0 && theDate <= this.endDate) {
          this.callback();
        } else if (this.endDate === 0 && theDate >= this.startDate) {
          this.callback();
        } else if (theDate >= this.startDate && theDate <= this.endDate) {
          this.callback();
        }
      }
    }

    return TimedCreative;

  })();

  if (window.Kargo == null) {
    window.Kargo = {};
  }

  window.Kargo.TimedCreative = TimedCreative;

}).call(this);
